### ISSUE TITLE
 calculateTransactionHash

### ISSUE THREAD

**Issue by OGKingD** [henryejemuta/laravel-monnify#3]
https://github.com/henryejemuta/laravel-monnify/blob/7840f1fb03f241e02af53e93aaa16fdb11ea2c38/src/Monnify.php#L604

There's a bug in the calculateTransactionHash method, **the casting of the amountPaid to float is returning a wrong hash** when compared with the one passed in the webhook payLoad,
_Consider either removing the type casting (float amountPaid) or fromat to 2DP, or just leave as is..._

Here's a dump of the values being sent..
[2020-09-04 21:01:29] local.DEBUG: MONNIFY
[2020-09-04 21:01:29] local.DEBUG: array (
  0 => 'my-secret-key',
  1 => 'MNFY|20200904214836|000639',
  2 => 100.0,
  3 => '04/09/2020 09:48:37 PM',
  4 => 'MNFY|20200904214836|000639',
)  

[2020-09-04 21:01:29] local.DEBUG: MINE  

[2020-09-04 21:01:29] local.INFO: array (
  0 => 'my-secret-key',
  1 => 'MNFY|20200904214836|000639',
  2 => '100.00',
  3 => '04/09/2020 09:48:37 PM',
  4 => 'MNFY|20200904214836|000639',
)  

The amount #100, monnify  is returning 1d.p cause of the type casting, thereby  returning a wrong hash

Monnify Library hash: 
006b4ccd4b28f6a38544b1b8f7ae23d86a0310be07506512c125dc5a44bc1874aa8592d3ef7516cb8aa26eafa848f4565f4743af12696d07db5cb075e86f1f41

![Screenshot_20200904_222327](https://user-images.githubusercontent.com/44497964/92285929-7e38a700-eefd-11ea-9e3b-00efe079b963.png)

with the proper amount in the proper format it returns the matching result...

My Computed hash:
eab30832a18aa73358454821ed2a6b795b0ec4c624d7683c5c76c180d28fd02346ef905d460bb7d3ce2095994e44e7d55d78ec7255b9a7a318336511bcaba4ed

**Comment by henryejemuta** [comment]
Thank for notifying us, this would be fixed in the update that would role out today

**Comment by Ferditech** [comment]
Please I need help if I can contact you via telegram please send your mail or handle

**Comment by henryejemuta** [comment]
> Please I need help if I can contact you via telegram please send your mail or handle

To talk on Telegram: [Click Here](https://t.me/henryejemuta)
